apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats-streaming.fullname" . }}
  labels:
    app: {{ include "nats-streaming.name" . }}
    chart: {{ include "nats-streaming.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.client }}
      targetPort: {{ .Values.service.port.client }}
      protocol: TCP
      name: client
    - port: {{ .Values.service.port.monitor }}
      targetPort: {{ .Values.service.port.monitor }}
      protocol: TCP
      name: monitor
  selector:
    app: {{ include "nats-streaming.name" . }}
    release: {{ .Release.Name }}
