apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "nats-streaming.fullname" . }}
  labels:
    app: {{ include "nats-streaming.name" . }}
    chart: {{ include "nats-streaming.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nats-streaming.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "nats-streaming.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.database.enabled }}
          args: [
            "--store SQL",
            "--sql_driver", "{{ .Values.database.driver }}",
            "--sql_source", "{{ .Values.database.connectionString }}"
          ]
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.monitorPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.monitorPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
